<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- <xacro:property name="prefix" value="${tf_prefix}/" />
    <xacro:property name="base_length" value="0.8" />
    <xacro:property name="base_width" value="0.8" />
    <xacro:property name="base_height" value="0.4" />
    <xacro:property name="wheel_radius" value="0.4" />
    <xacro:property name="wheel_length" value="0.2" /> -->

    <link name="${prefix}base_footprint" />

    <link name="${prefix}base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="100.0" x="${base_length}" y="${base_width}" z="${base_height}"
                          o_xyz="0 0 ${base_height / 2.0}" o_rpy="0 0 0" />
    </link>

    <xacro:macro name="wheel_link" params="prefix suffix">
        <link name="${prefix}${suffix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}" />
                </geometry>
                <surface>
      		<friction>
        		<ode>
          		<mu>10.0</mu>             <!-- Static friction -->
          		<mu2>8.0</mu2>           <!-- Dynamic friction -->
        		</ode>
      		</friction>
    		</surface>
                <origin xyz="0 0 0" rpy="0 0 0" />
            </collision>
            <xacro:cylinder_inertia m="20.0" r="${wheel_radius}" l="${wheel_length}"
                                   o_xyz="0 0 0" o_rpy="${pi / 2.0} 0 0" />
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="${prefix}" suffix="right" />
    <xacro:wheel_link prefix="${prefix}" suffix="left" />

    <link name="${prefix}caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius / 2.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius / 2.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:sphere_inertia m="2.0" r="${wheel_radius / 2.0}"
                             o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>
    
    <link name="${prefix}caster_wheel_link2">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius / 2.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius / 2.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:sphere_inertia m="2.0" r="${wheel_radius / 2.0}"
                             o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>

    <joint name="${prefix}base_joint" type="fixed">
        <parent link="${prefix}base_footprint" />
        <child link="${prefix}base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <joint name="${prefix}base_right_wheel_joint" type="continuous">
        <parent link="${prefix}base_link" />
        <child link="${prefix}right_wheel_link" />
        <origin xyz="0 ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="${prefix}base_left_wheel_joint" type="continuous">
        <parent link="${prefix}base_link" />
        <child link="${prefix}left_wheel_link" />
        <origin xyz="0 ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="${prefix}base_caster_wheel_joint" type="fixed">
        <parent link="${prefix}base_link" />
        <child link="${prefix}caster_wheel_link" />
        <origin xyz="${base_length / 3.0} 0 ${-wheel_radius / 2.0}" rpy="0 0 0" />
    </joint>
    
    <joint name="${prefix}base_caster_wheel_joint2" type="fixed">
        <parent link="${prefix}base_link" />
        <child link="${prefix}caster_wheel_link2" />
        <origin xyz="${-base_length / 3.0} 0 ${-wheel_radius / 2.0}" rpy="0 0 0" />
    </joint>

</robot>
