<?xml version="1.0"?>
<robot name="two_wheel_robot" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- ========== PARAMETERS ========== -->
  <xacro:property name="body_length" value="0.4"/>
  <xacro:property name="body_width"  value="0.3"/>
  <xacro:property name="body_height" value="0.1"/>
  <xacro:property name="body_mass"   value="5.0"/>

  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_width"  value="0.05"/>
  <xacro:property name="wheel_mass"   value="0.5"/>
  <xacro:property name="wheel_offset_y" value="0.15"/>
  <xacro:property name="wheel_offset_z" value="0.025"/>

  <xacro:property name="caster_radius" value="0.03"/>
  <xacro:property name="caster_mass" value="0.1"/>
  <xacro:property name="caster_offset_x" value="-0.15"/>
  <xacro:property name="caster_offset_z" value="0.03"/>

  <!-- ========== MACROS ========== -->
  <xacro:macro name="inertial_box" params="mass x y z">
    <inertial>
      <mass value="${mass}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="${(1/12.0)*${mass}*(${y}*${y} + ${z}*${z})}"
               iyy="${(1/12.0)*${mass}*(${x}*${x} + ${z}*${z})}"
               izz="${(1/12.0)*${mass}*(${x}*${x} + ${y}*${y})}"
               ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </xacro:macro>

  <!-- ========== BASE LINK ========== -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <origin xyz="0 0 ${body_height/2}" rpy="0 0 0"/>
      <material name="blue">
        <color rgba="0 0 1 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <origin xyz="0 0 ${body_height/2}"/>
    </collision>
    <xacro:inertial_box mass="${body_mass}" x="${body_length}" y="${body_width}" z="${body_height}"/>
  </link>

  <!-- ========== LEFT WHEEL ========== -->
  <link name="left_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <origin xyz="0 ${wheel_offset_y} ${wheel_offset_z}" rpy="0 1.5708 0"/>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <origin xyz="0 ${wheel_offset_y} ${wheel_offset_z}" rpy="0 1.5708 0"/>
    </collision>
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0"
               izz="0.0001"/>
    </inertial>
  </link>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="0 ${wheel_offset_y} ${wheel_offset_z}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- ========== RIGHT WHEEL ========== -->
  <link name="right_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <origin xyz="0 -${wheel_offset_y} ${wheel_offset_z}" rpy="0 1.5708 0"/>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <origin xyz="0 -${wheel_offset_y} ${wheel_offset_z}" rpy="0 1.5708 0"/>
    </collision>
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0"
               izz="0.0001"/>
    </inertial>
  </link>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="0 -${wheel_offset_y} ${wheel_offset_z}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- ========== CASTER WHEEL ========== -->
  <link name="caster_wheel">
    <visual>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <origin xyz="${caster_offset_x} 0 ${caster_offset_z}"/>
      <material name="grey">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <origin xyz="${caster_offset_x} 0 ${caster_offset_z}"/>
    </collision>
    <inertial>
      <mass value="${caster_mass}"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.00001" iyy="0.00001" izz="0.00001"
               ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </link>

  <joint name="caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_wheel"/>
    <origin xyz="${caster_offset_x} 0 ${caster_offset_z}"/>
  </joint>

</robot>
